### PR TITLE
Feat/request api key page

### LINKED ISSUE #61: full stack: create page for request an API key
### **Description**:  
Develop a new page titled **"Request an API Key"**, accessible via:  
1. A link in the **sidebar**.  
2. A link/button on the homepage (`/`), near the **Connect/Disconnect** button.

This page will allow users to request an API key without requiring wallet connection.  

The form should include the following fields:  
- `Name`  
- `Last Name`  
- `Email`  
- `Type` (dropdown with `Company` or `Individual`)  
- `Description`  

---

### Firebase

In the issue request, **your email address must be included**, otherwise it will be discarded. This is so we can give you access to firebase

Enter the following link: https://console.firebase.google.com/u/0/project/trustless-work/overview

---

### **Example of 'How to insert data in firebase'**
[Check this example branch](https://github.com/Tico4Chain-Coders/dApp-Trustless-Work/tree/example/how-to-integrate-firebase)

---

### **Requirements**:  
1. **Form Creation**:  
   - Build a form with the specified fields and proper UI validation for each input.  
   - Ensure all fields are required.  

2. **Firebase Integration**:  
   - Store the form data in the **`api keys` collection** in Firebase.  
   - Validate the email field to ensure it is **unique** in the collection. Only one API key request per email should be allowed.

3. **Validation**:  
   - Check if the email already exists in the `api keys` collection. If it does, display an error message:  
     _"An API key has already been requested with this email."_  

4. **Navigation**:  
   - Add a link to this page in the **sidebar**.  
   - Add a link/button to this page on the homepage (`/`), near the **Connect/Disconnect** button.  

5. **UI Standards**:  
   - Follow consistent design standards, matching the existing styling and layout of the application.  

---

### **Validations**:  
1. Ensure form validation for all required fields.  
2. Confirm the email is unique in the `api keys` collection.  
3. Validate correct Firebase insertion on successful form submission. 
4. It should works on light / dark mode.
5. Must be fully responsive. 

---

### **Tests**:  
1. **Form Validation**: Ensure all fields are required and display appropriate error messages when invalid.  
2. **Email Validation**: Test cases for emails already in the collection and ensure no duplicates are allowed.  
3. **Firebase Integration**: Verify data is correctly stored in the `api keys` collection after submission.  
4. **UI Navigation**: Confirm links in the sidebar and homepage (`/`) navigate to the new page.  

⚠️ **Please follow the guidelines for requesting an issue, launching commits, and describing PRs. Otherwise, they will be ignored.** ⚠️

### PR DESCRIPTION
**Pull request by respp**
<p align="center"> CLR-S (2) </p>

# Pull Request | Trustless Work

## 1. Issue Link

[](https://github.com/Tico4Chain-Coders/dApp-Trustless-Work/issues/61)

- Closes #61 

---

## 2. Brief Description of the Issue

The problem involves developing a new page titled **"Request an API Key"** that allows users to submit requests for an API key without the need to connect their wallet. The form must validate all required fields, ensure the uniqueness of the email in the Firebase `api keys` database, and integrate seamlessly with the existing design and functionality of the application. Additionally, it must meet responsiveness and accessibility standards.

---

## 3. Type of Change

Mark with an `x` all the checkboxes that apply (like `[x]`).

- [ ] 📝 Documentation (updates to README, docs, or comments)
- [ ] 🐛 Bug fix (non-breaking change which fixes an issue)
- [x] 👌 Enhancement (non-breaking change which adds functionality)
- [ ] 💥 Breaking change (fix or feature that would cause existing functionality to change)

---

## 4. Changes Made

- Modified the page.tsx in /app to include the "Request an API Key" button.
- Added the "request-api-key" folder.
- Added the contact module with the contact form and the hook to add entries to the database and perform the respective validations.

---

## 5. Evidence Before Solution

[]

[Loom Video - Before Solution](LINK_TO_VIDEO_BEFORE)(https://www.loom.com/share/d6e9eaa8111e4d35b59c68b32ab7accd)

---

## 6. Evidence After Solution

[[Loom Video - After Solution](LINK_TO_VIDEO_AFTER)](https://www.loom.com/share/d6ec01f9089d4c3d98fb174b1e036d7c)

---

## 7. Important Notes

- the contact hook is responsible for managing database entries to ensure proper validations.

# If you don't use this template, you'd be ignored

### CODE REVIEW

**Comment by armandocodecr** [comment]
Before reviewing the technical part, I would like to ask you for a couple of changes in the UI. These changes are as follows:

1. The header and sidebar of the page should not disappear when entering the url “/request-api-key”. For example, if you enter this url “/dashboard/escrow/fund-escrow”, you will notice that the page content is displayed along with the header and sidebar. The above should be the same for the “/request-api-key” page.
3. The “Request an API Key” button only appears when the user does not have his wallet connected. This button should appear both when the user does not have his wallet connected and when he has it connected.
4. Change the text of the “Fund Escrow” form button to “Submit Request”.
5. Change the content of the toast shown when submitting the form, because it says “Your escrow has been funded successfully”, which is not correct for the context of the form. You should place a message like “Your API key request has been submitted successfully.”

**Review by armandocodecr — CHANGES_REQUESTED** [review]
Before reviewing the technical part, I would like to ask you for a couple of changes in the UI. These changes are as follows:

1. The header and sidebar of the page should not disappear when entering the url “/request-api-key”. For example, if you enter this url “/dashboard/escrow/fund-escrow”, you will notice that the page content is displayed along with the header and sidebar. The above should be the same for the “/request-api-key” page.
2. Change the text of the “Fund Escrow” form button to “Submit Request”.
3. Change the content of the toast shown when submitting the form, because it says “Your escrow has been funded successfully”, which is not correct for the context of the form. You should place a message like “Your API key request has been submitted successfully.”

**Comment by respp** [comment]
already made the changes requested

**Comment by armandocodecr** [comment]
Thank you for your changes! Your code is ready to be merged. 🚀

**Pull request merged**
