### PR TITLE
refactor(escrow): modularize escrow creation components and add stepp…

### LINKED ISSUE #54: frontend: merge create escrow and initialize escrow with steps component
### **Description**:  
Merge the functionalities from [Issue #28](https://github.com/Tico4Chain-Coders/dApp-Trustless-Work/issues/28) and [Issue #27](https://github.com/Tico4Chain-Coders/dApp-Trustless-Work/issues/27) into a single component. The combined feature will include a stepper where:  
1. **Step 1**: Implements the "Service Details Form" ([Issue #28](https://github.com/Tico4Chain-Coders/dApp-Trustless-Work/issues/28)).  
2. **Step 2**: Incorporates the "Steps for Milestone Configuration" ([Issue #27](https://github.com/Tico4Chain-Coders/dApp-Trustless-Work/issues/27)).  

The goal is to ensure a seamless user experience where users can move between the two steps effortlessly.  

---  

### **Requirements**:  
1. **Stepper Integration**: Use a stepper to transition between Step 1 and Step 2. The stepper should be visually clear and intuitive.  
2. **Form Design**:  
   - **Step 1**: Utilize the form design outlined in [Issue #28](https://github.com/Tico4Chain-Coders/dApp-Trustless-Work/issues/28).  
   - **Step 2**: Follow the milestone step logic and UI specified in [Issue #27](https://github.com/Tico4Chain-Coders/dApp-Trustless-Work/issues/27).  
3. **State Management**: Ensure data entered in Step 1 persists and can be accessed in Step 2.

---  

### **Validations**:  
1. Confirm the stepper allows smooth navigation between Step 1 and Step 2.  
2. Validate that the data from Step 1 (Service Details Form) is correctly captured and retained.  
3. Verify that the steps for milestone configuration function as described in [Issue #27](https://github.com/Tico4Chain-Coders/dApp-Trustless-Work/issues/27).
4. It should works on light / dark mode.
5. Must be fully responsive.

---  

### **Tests**:  
1. **Integration Testing**: Ensure the stepper integrates and transitions correctly between the steps.  
2. **State Testing**: Test data persistence between Step 1 and Step 2.  
3. **UI Testing**: Check for consistent and visually appealing design for both steps.  

---  

### **Recommendation**:  
- Use a state management library (zustand) to handle form data across steps.  
- Maintain a clean and minimal design for the stepper to avoid clutter.  

⚠️ **Please follow the guidelines for requesting an issue, launching commits, and describing PRs. Otherwise, they will be ignored.** ⚠️

### PR DESCRIPTION
**Pull request by 0xdevcollins**
<p align="center"> CLR-S (2) </p>

# Pull Request | Trustless Work

## 1. Issue Link

- Closes #54
---

## 2. Brief Description of the Issue

This PR combines the functionalities of Issue #28  and Issue #27  into a unified component with a stepper interface.

Step 1:Create Escrow as per Issue #28.
Step 2: Milestone configuration logic and UI from Issue #27.
The goal is to create a seamless user experience with smooth navigation between the steps while ensuring data persistence and responsive design.

---

## 3. Type of Change

Mark with an `x` all the checkboxes that apply (like `[x]`).

- [ ] 📝 Documentation (updates to README, docs, or comments)
- [ ] 🐛 Bug fix (non-breaking change which fixes an issue)
- [x] 👌 Enhancement (non-breaking change which adds functionality)
- [ ] 💥 Breaking change (fix or feature that would cause existing functionality to change)

---

## 4. Changes Made

- Integrated a stepper component to switch between Create escrow and initialize escrow.
- Added Zustand state management to persist data between the steps.
- Ensured full responsiveness and compatibility with both light and dark mode.

---

## 5. Evidence Before Solution

[Loom Video - Before Solution](https://www.loom.com/share/fc44ac6791654e51ba19a753d785680d?sid=0cf05218-d120-40c0-8e82-e9d5133a6bcc)

---

## 6. Evidence After Solution

[Loom Video - After Solution](https://www.loom.com/share/3e3c354ac3fb4c2f8d1a711e9a72d56b?sid=a8796646-953d-4186-bc3c-cb235c610ca5)

---

## 7. Important Notes

- Note 1
- Note 2
- Note 3

# If you don't use this template, you'd be ignored

### CODE REVIEW

**Comment by JoelVR17** [comment]
@0xdevcollins please complete all the PR description. If not, I cannot merge it

**Comment by JoelVR17** [comment]
> @0xdevcollins please complete all the PR description. If not, I cannot merge it

- The behavior is correct, but not in that way. I'll explain you below:

1 - As you see in this issue:

[feat: add steps progress component with horizontal bars](https://github.com/Tico4Chain-Coders/dApp-Trustless-Work/pull/37#top)

image

I need the same component in order to show the progress, exmp:

(STEP 1 - CREATE ESCROW) -> WHEN THE USER CLICK ON THE BUTTON, GO TO THE ANOTHER STEP -> (THE FORM DATA OF INITIALIZE ESCROW, SHOULD BE SAVED IN ZUSTAND, BECAUSE THE USER CAN GO BACK TO THE FIRST STEP, AND THE FORM SHOULD KEEP THE DATA)
image

(STEP 2 - INITIALIZE ESCROW)
image

**Comment by 0xdevcollins** [comment]
> @0xdevcollins please complete all the PR description. If not, I cannot merge it

I have completed the PR description. I am very sorry for the delay :)

**Comment by JoelVR17** [comment]
> > @0xdevcollins please complete all the PR description. If not, I cannot merge it
> 
> I have completed the PR description. I am very sorry for the delay :)
> 

Brow, please follow the screenshots that I've left you

I need the steps on the left side and the content in the right side.

Please use just the vertical steps, not the horizontal.

When you do those changes, please uptade the loom video, in order to check the interface

**Comment by 0xdevcollins** [comment]
Am I free to to modify the step component?

**Comment by JoelVR17** [comment]
> Am I free to to modify the step component?

If you need it, but only in the behavior, the appearance not

**Comment by 0xdevcollins** [comment]
I created a different component for the Steps to suite your description since I am not to change the appearance of the available one.

**Before**(With the available Step component): https://www.loom.com/share/7ae094b86a6549b494cfd42c8b1f1297?sid=cfca2f06-5a73-45c9-a02a-95b505f0931f


**After**: https://www.loom.com/share/53dfe8a87442412c8ab9ea9708491f38?sid=b0d00eb4-5304-4481-8332-cff380e09629

**Comment by JoelVR17** [comment]
> I created a different component for the Steps to suite your description since I am not to change the appearance of the available one.
> 
> **Before**(With the available Step component): https://www.loom.com/share/7ae094b86a6549b494cfd42c8b1f1297?sid=cfca2f06-5a73-45c9-a02a-95b505f0931f
> 
> **After**: https://www.loom.com/share/53dfe8a87442412c8ab9ea9708491f38?sid=b0d00eb4-5304-4481-8332-cff380e09629

Thanks man, merged!

**Pull request merged**
