### PR TITLE
create page for dashboard 

### LINKED ISSUE #59: frontend: create page for dashboard
### **Description**:  
Create a set of reusable components for the dashboard page. These components should follow the design and functionality structure similar to the [Shadcn Dashboard Example](https://ui.shadcn.com/examples/dashboard). The components should be placeholders for future data and can be easily integrated with real data once the backend functionalities are implemented. 

---

### **Requirements**:  
1. **Dashboard Layout**: Implement a responsive layout with sections for key metrics and data visualization.
2. **Reusable Components**: Create modular components that can be reused across different sections of the dashboard, such as:
   - **Card**: Display key metrics like Total Users, Revenue, etc.
   - **Charts**: Placeholder components for charts such as line charts, bar charts, etc.
   - **Table**: A table to display a list of recent activities or transactions.
   - **Progress Bars**: Show progress for tasks, payments, etc.
   - **Sidebar**: A sidebar to navigate between different sections of the dashboard.
3. **Styling**: Ensure that the components are styled similarly to the Shadcn dashboard, with a clean and professional look.
4. **Responsive Design**: Make sure that the dashboard components are responsive and adapt well to different screen sizes.
5. **Icons**: Use appropriate icons for buttons, actions, and indicators (e.g., from [react-icons](https://react-icons.github.io/react-icons/)).
6. **Placeholder Data**: Use dummy data for now, with future integrations to replace them once the backend is ready.

---

### **Validations**:  
1. Ensure that each component (Card, Chart, Table, Progress Bar, Sidebar) is reusable and modular.
2. Validate that the layout adjusts properly to different screen sizes.
3. Confirm that the placeholder data is displayed correctly for each component.
4. Ensure the navigation sidebar allows switching between different sections.
4. It should works on light / dark mode.
5. Must be fully responsive.

---

### **Tests**:  
1. **Component Rendering**: Verify that each component (Card, Chart, Table, etc.) renders correctly.
2. **Responsiveness Testing**: Check that the layout and components adapt to different screen sizes (mobile, tablet, desktop).
3. **UI Testing**: Ensure that all UI elements (icons, buttons, charts) are properly styled and aligned.

⚠️ **Please follow the guidelines for requesting an issue, launching commits, and describing PRs. Otherwise, they will be ignored.** ⚠️

### PR DESCRIPTION
**Pull request by Jemiiah**
<p align="center"> CLR-S (2) </p>

# Pull Request | Trustless Work

## 1. Issue Link

- Closes #59

---

## 2. Brief Description of the Issue

- Implemented dashboard UI component and page following shardcn UI
- chart, layout, Metric card e.t.c

---

## 3. Type of Change

Mark with an `x` all the checkboxes that apply (like `[x]`).

- [ ] 📝 Documentation (updates to README, docs, or comments)
- [ ] 🐛 Bug fix (non-breaking change which fixes an issue)
- [x] 👌 Enhancement (non-breaking change which adds functionality)
- [ ] 💥 Breaking change (fix or feature that would cause existing functionality to change)

---

## 4. Changes Made

- Dashboard screen
- Chart components 
- MetricCard components

---

## 5. Evidence Before Solution

[Loom Video - Before Solution](LINK_TO_VIDEO_BEFORE)

---

## 6. Evidence After Solution

Screenshot from 2024-12-19 07-16-23

---

### CODE REVIEW

**Review by armandocodecr — CHANGES_REQUESTED** [review]
Overall everything looks very good. You just forgot to create and add to the dashboard a progress bar component, which is requested in the issue.

Also, take a look at the following image:
Screenshot 2024-12-19 at 11 41 46 AM

Do you notice that around the dashboard container there is a gray border? That border should not be noticeable. In fact, the entire dashboard container should be the color of that border. This is something that you can notice in the other pages.

**Comment by armandocodecr** [comment]
And please run the command “npm run build” and verify that the “prettier” does not throw any error.

**Comment by Jemiiah** [comment]
Screenshot from 2024-12-20 14-44-26

**Comment by armandocodecr** [comment]
Your changes are ready to be merged. Thanks for your contribution! 🚀

**Pull request merged**
